import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
import { StaticPage } from "@/components/content/StaticPage";
import { JsonLd } from "@/components/content/JsonLd";

export const metadata = pageMetadata({
  title: "FAQ",
  description:
    "Answers to common questions about MK VoiceKit: whether you can download the audio, why voices differ, what happens to your text, PDF support, and more.",
  path: "/faq",
});

interface QA {
  q: string;
  /** Plain-text answer used for the FAQPage structured data. */
  a: string;
}

const FAQS: QA[] = [
  {
    q: "Can I download the audio as an MP3?",
    a: "No. MK VoiceKit uses the speech engine built into your browser, and that engine plays sound directly to your speakers without giving any program a file to save. There is no honest way to turn that into a downloadable MP3, so there is no download button. If you need real audio files, you would need a server-side or neural text-to-speech service, which is a possible future direction but is not promised.",
  },
  {
    q: "Is it really free? What's the catch?",
    a: "It is free and open source under the MIT license, with no account and no paywall. The core reading features run in your browser, so they cost nothing to run. The only part that touches a paid service is the optional AI text tools, which have a small daily limit; you can lift that by adding your own key.",
  },
  {
    q: "Do you upload my text or files to a server?",
    a: "No, not for the core features. Reading text aloud, extracting text from a PDF, and parsing subtitles all happen on your device. The only time text leaves your browser is if you deliberately run one of the optional AI tools, and even then the text is processed and discarded, not stored.",
  },
  {
    q: "Why are the available voices different on my other computer?",
    a: "The voices come from your operating system and browser, not from MK VoiceKit. Windows, macOS, iOS, Android and the various Linux setups each ship different voices, and browsers expose them differently. That is why the same text can sound different from one device to the next, and why you can add more voices through your operating system's settings.",
  },
  {
    q: "The voice list is empty. What's wrong?",
    a: "Some browsers load voices asynchronously, so they can appear a moment after the page loads; there is a reload-voices control for that. If it stays empty, your operating system may have no speech voices installed, or the browser may not support the Web Speech API. The workspace shows per-system hints when this happens.",
  },
  {
    q: "Can it read a scanned PDF?",
    a: "Only if the PDF has a real text layer. Many scanned documents are just images of pages with no selectable text, and MK VoiceKit does not do OCR, so there is nothing to read. When that happens you'll see an honest 'no extractable text' message rather than silence.",
  },
  {
    q: "Does it work offline?",
    a: "Yes, for the core features, after the first load. Because speech is generated by your browser, you can read text aloud without a network connection. The optional AI tools do need a connection, since they call a model.",
  },
  {
    q: "What are the AI tools, and are they required?",
    a: "They are optional helpers that can rewrite, simplify, summarise, translate or restructure text before you listen. They are entirely separate from the reading features, which work without them. If no AI service is available, the tools show an honest 'AI unavailable' state instead of faking a result.",
  },
  {
    q: "Do I need an API key?",
    a: "No. The AI tools work out of the box up to a small daily limit. If you want to go beyond that limit, you can paste your own Vercel AI Gateway key in Settings; it stays on your device and is sent only with requests you start yourself.",
  },
  {
    q: "How do the keyboard shortcuts work?",
    a: "Space plays or pauses, Escape stops, the left and right arrows move by sentence, Shift with the arrows moves by paragraph, and the up and down arrows change the speed. Press the question-mark key to open a dialog listing every shortcut. Space is ignored while you are typing in a control, so it won't interrupt you mid-edit.",
  },
  {
    q: "Where is my history stored, and can I delete it?",
    a: "History, presets and the listening queue are stored locally in your browser using IndexedDB. Nothing is on a server. You can export everything to a file, import it back, or clear all of it from the Settings page.",
  },
  {
    q: "Which browsers are supported?",
    a: "Any modern browser with the Web Speech API: recent versions of Chrome, Edge, Safari and Firefox all work, on desktop and mobile. The exact voices and whether word-level highlighting is available depend on the browser and operating system.",
  },
];

function faqJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQS.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };
}

export default function FaqPage() {
  return (
    <>
      <JsonLd data={faqJsonLd()} />
      <StaticPage
        title="Frequently asked questions"
        lede="Straight answers, including the one everyone asks first."
        path="/faq"
        crumbLabel="FAQ"
      >
        <dl className="flex flex-col gap-3">
          {FAQS.map((item) => (
            <div
              key={item.q}
              className="rounded-xl border border-border bg-surface p-5"
            >
              <dt className="text-lg font-bold">{item.q}</dt>
              <dd className="mt-2 text-text-muted">{item.a}</dd>
            </div>
          ))}
        </dl>

        <p className="mt-8 text-text-muted">
          Still stuck? The <Link href="/docs" className="text-primary hover:underline">docs</Link>{" "}
          go deeper, and you can always{" "}
          <Link href="/contact" className="text-primary hover:underline">
            get in touch
          </Link>
          .
        </p>
      </StaticPage>
    </>
  );
}
